---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ms-continuus-secrets
  namespace: ms-continuus
spec:
  provider: azure
  secretObjects:
    - secretName: ms-continuus
      type: Opaque
      data:
        - key: GITHUB_TOKEN
          objectName: ms-continuus-github-token
        - key: STORAGE_ACCOUNT_CON_STRING
          objectName: ms-continuus-connection
  parameters:
    keyvaultName: sdp-bicep-dev-kv # The name of the Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "542c2a81-b80c-4663-91c6-d968dcb69b2b" # sdp-bicep-dev-mi
    tenantId: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
    objects: |
      array:
        - |
          objectName: ms-continuus-github-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: ms-continuus-connection
          objectType: secret
          objectVersion: ""
