---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml
  - apps.yaml
  - cluster-issuer.yaml
  # - ../../infrastructure  # For testing
patchesStrategicMerge:
  - ingress-nginx-patch.yaml
