---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.19
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    adminUser:
      create: true
      username: admin
      passwordHash: "$2a$12$fJEm0XI3SOpZvXO31fYjy.tJN1umbb.opO.bX4E.q6bD3CwiJvF5q"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: weave.dev.sdp.equinor.com
      hosts:
        - host: weave.dev.sdp.equinor.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: letsencrypt-nginx-staging
          namespace: cert-manager
          hosts:
            - weave.dev.sdp.equinor.com
