apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitaly
    release: gitlab
  name: repo-data-gitlab-gitaly-0
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: managed-csi-premium
  volumeMode: Filesystem
  volumeName: gitlab-repository-expanded
