---
apiVersion: v1
kind: Pod
metadata:
  name: ms-continuus-secrets-mount
  namespace: ms-continuus
spec:
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
  containers:
    - name: busybox
      image: busybox:1.28
      imagePullPolicy: Always
      command:
        - "/bin/sleep"
        - "10000"
      securityContext:
        runAsUser: 10000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
      livenessProbe:
        exec:
          command:
            - "/bin/ls"
            - "/mnt/secrets-store"
        initialDelaySeconds: 5
        periodSeconds: 5
      volumeMounts:
        - name: secrets-store-mount
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-mount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "ms-continuus-secrets"
