---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 6.20.*
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h
  values:
    provider: azure
    azure:
      tenantId: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      subscriptionId: b18da12e-efa1-4642-8fec-b6580b00212c
      useManagedIdentityExtension: true
