apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/migrated-to: disk.csi.azure.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  name: gitlab-repository-expanded
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  azureDisk:
    cachingMode: None
    diskName: gitlab-repository-expanded
    diskURI: /subscriptions/b18da12e-efa1-4642-8fec-b6580b00212c/resourceGroups/mc_sdp-bicep-dev_sdp-bicep-dev-aks_norwayeast/providers/Microsoft.Compute/disks/gitlab-repository-expanded
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 512Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: repo-data-gitlab-gitaly-0
    namespace: gitlab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi-premium
  volumeMode: Filesystem
