---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  chart:
    spec:
      version: 7.0.2
  values:
    gitlab:
      webservice:
        ingress:
          annotations:
            kubernetes.io/tls-acme: "true"
            external-dns.alpha.kubernetes.io/hostname: gitlab.dev.sdpaks.equinor.com
      migrations:
        psql:
          host: sdp-bicep-dev-psql14.postgres.database.azure.com
    global:
      psql:
        host: sdp-bicep-dev-psql14.postgres.database.azure.com
      hosts:
        domain: dev.sdpaks.equinor.com
        https: true
        gitlab:
          name: gitlab.dev.sdpaks.equinor.com
        registry:
          name: registry.dev.sdpaks.equinor.com
      email:
        display_name: "Dev GitLab Equinor"
