---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/gitlab
  - secret-provider.yaml
  - gitlab-repo-pv.yaml
patchesStrategicMerge:
  - helm-release-patch.yaml
