---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  parameters:
    keyvaultName: sdp-bicep-dev-kv # The name of the Key Vault
    userAssignedIdentityID: "542c2a81-b80c-4663-91c6-d968dcb69b2b" # sdp-bicep-dev-mi
