---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./infrastructure/cert-manager/certs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
