---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  path: "./infrastructure/cert-manager/controller"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-repo

