---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    provider: azure
    domainFilters: ["dev.sdp.equinor.com"]
    azure:
      tenantId: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
      subscriptionId: b18da12e-efa1-4642-8fec-b6580b00212c
      resourceGroup: sdp-bicep-dev
      useManagedIdentityExtension: true
