---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    provider: azure
    domainFilters: ["dev.sdpaks.equinor.com"]
    azure:
      resourceGroup: sdp-bicep-dev
      userAssignedIdentityID: 542c2a81-b80c-4663-91c6-d968dcb69b2b # Kubelet MI
