---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    domainFilters: ["dev.sdp.equinor.com"]
    azure:
      secretName: azure-dns-config-file
