---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitlab-secrets
  namespace: gitlab
spec:
  provider: azure
  secretObjects:
    - secretName: gitlab-smtp-secret
      type: Opaque
      data:
        - key: password
          objectName: gitlab-smtp-secret
    - secretName: gitlab-psql-secret
      type: Opaque
      data:
        - key: username
          objectName: psql-admin-login
        - key: password
          objectName: psql-admin-password
    - secretName: gitlab-rails-storage
      type: Opaque
      data:
        - key: connection
          objectName: gitlab-rails-storage
    - secretName: gitlab-registry-storage
      type: Opaque
      data:
        - key: config
          objectName: gitlab-registry-storage
    - secretName: gitlab-backup-storage
      type: Opaque
      data:
        - key: config
          objectName: gitlab-backup-storage
    - secretName: gitlab-azure-saml
      type: Opaque
      data:
        - key: provider
          objectName: gitlab-azure-saml
    - secretName: gitlab-ssh-keys
      type: Opaque
      data:
        - key: ssh_host_ecdsa_key
          objectName: ssh-host-ecdsa-key
        - key: ssh_host_ecdsa_key.pub
          objectName: ssh-host-ecdsa-key-pub
        - key: ssh_host_ed25519_key
          objectName: ssh-host-ed25519-key
        - key: ssh_host_ed25519_key.pub
          objectName: ssh-host-ed25519-key-pub
        - key: ssh_host_rsa_key
          objectName: ssh-host-rsa-key
        - key: ssh_host_rsa_key.pub
          objectName: ssh-host-rsa-key-pub
    - secretName: gitlab-rails-secret
      type: Opaque
      data:
        - key: secrets.yml
          objectName: gitlab-rails-secret
    - secretName: gitlab-sdp-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: gitlab-sdp-tls
        - key: tls.key
          objectName: gitlab-sdp-tls
  parameters:
    keyvaultName: sdp-bicep-prod-kv # The name of the Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "b1a28b94-8069-4ca0-80b6-27d3bf9eb2e3" # sdp-bicep-prod-mi
    tenantId: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
    objects: |
      array:
        - |
          objectName: gitlab-smtp-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: psql-admin-login
          objectType: secret
          objectVersion: ""
        - |
          objectName: psql-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-rails-storage
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-registry-storage
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-backup-storage
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-azure-saml
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-ecdsa-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-ecdsa-key-pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-ed25519-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-ed25519-key-pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-rsa-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: ssh-host-rsa-key-pub
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-rails-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: gitlab-sdp-tls
          objectType: secret
          objectVersion: ""
