---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "$2y$10$IfxMsTyqi970MS9f9HCOguDDfXUs0FYXMnSYwurgMepUWVaBklv5G"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        external-dns.alpha.kubernetes.io/hostname: weave.prod.sdpaks.equinor.com
      hosts:
        - host: weave.prod.sdpaks.equinor.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: weave-tls
          hosts:
            - weave.prod.sdpaks.equinor.com
